/**
 * scripts/inline-html.js
 * 构建脚本：将 public/index.html 内联为 src/html.js ES module
 * 用于 Cloudflare Workers 直接返回前端 HTML
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const htmlPath = join(root, 'public', 'index.html');
const outputPath = join(root, 'src', 'html.js');

try {
  const html = readFileSync(htmlPath, 'utf-8');
  // 转义反引号和 ${} 防止模板字符串冲突
  const escaped = html.replaceAll('`', '\\`').replaceAll('${', '\\${');
  const content = `/**\n * Auto-generated by scripts/inline-html.js\n * DO NOT EDIT — changes to public/index.html will be overwritten\n */\nconst HTML = \`${escaped}\`;\nexport default HTML;\n`;
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✅ 已生成 ${outputPath} (${(Buffer.byteLength(content) / 1024).toFixed(1)} KB)`);
} catch (err) {
  console.error('❌ 构建失败:', err.message);
  process.exit(1);
}