/**
 * Auto-generated by scripts/inline-html.js
 * DO NOT EDIT — changes to public/index.html will be overwritten
 */
const HTML = `<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600&family=Source+Code+Pro:wght@400;500&display=swap" rel="stylesheet">
<title>CF-Workers-SUB-Next</title>
<style>
:root, [data-theme="light"] {
  --bg: #ffffff; --bg2: #ffffff; --bg3: #f6f8fb;
  --border: #e5edf5; --text: #061b31; --text2: #64748d;
  --accent: #533afd; --accent-hover: #4434d4; --accent2: #533afd;
  --green: #108c3d; --red: #ea2261; --orange: #9b6829;
  --shadow: rgba(23,23,23,0.08) 0px 15px 35px -10px;
  --shadow-sm: rgba(23,23,23,0.06) 0px 3px 6px;
  --shadow-brand: rgba(50,50,93,0.25) 0px 30px 45px -30px, rgba(0,0,0,0.1) 0px 18px 36px -18px;
  --side-bg: #f6f8fb;
}
[data-theme="dark"] {
  --bg: #0d1117; --bg2: #161b22; --bg3: #1c2431;
  --border: #2a3341; --text: #e6edf3; --text2: #8b98ab;
  --accent: #7c68ff; --accent-hover: #9484ff; --accent2: #7c68ff;
  --green: #3fb950; --red: #f8517c; --orange: #d29922;
  --shadow: rgba(0,0,0,0.45) 0px 15px 35px -10px;
  --shadow-sm: rgba(0,0,0,0.3) 0px 3px 6px;
  --shadow-brand: rgba(0,0,0,0.55) 0px 30px 45px -30px;
  --side-bg: #10151c;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: 'Source Sans 3', -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
  background: var(--bg); color: var(--text);
  line-height: 1.47059; font-weight: 400;
  letter-spacing: -0.022em;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
/* ===== Sidebar Layout ===== */
.app-shell { display: flex; min-height: 100vh; }
.sidebar {
  width: 208px; flex-shrink: 0;
  background: var(--side-bg); border-right: 1px solid var(--border);
  padding: 18px 12px; display: flex; flex-direction: column; gap: 2px;
  position: sticky; top: 0; height: 100vh; overflow-y: auto;
}
.sidebar .logo {
  font-weight: 600; font-size: 15px; letter-spacing: -0.02em;
  color: var(--text); padding: 2px 10px 16px;
}
.sidebar .logo span { color: var(--accent); }
.sgroup { font-size: 10px; color: var(--text2); letter-spacing: .1em; text-transform: uppercase; padding: 14px 10px 5px; font-weight: 600; }
.nav-tab {
  display: flex; align-items: center; gap: 9px;
  padding: 7px 10px; cursor: pointer;
  color: var(--text2); border-radius: 5px;
  font-size: 13.5px; font-weight: 400; white-space: nowrap;
  transition: all .15s;
}
.nav-tab:hover { color: var(--accent); background: rgba(83,58,253,0.05); }
[data-theme="dark"] .nav-tab:hover { background: rgba(124,104,255,0.1); }
.nav-tab.active { color: var(--accent); background: rgba(83,58,253,0.09); font-weight: 500; }
[data-theme="dark"] .nav-tab.active { background: rgba(124,104,255,0.16); }
.sidebar-footer { margin-top: auto; padding-top: 14px; display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.main-col { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  padding: 7px 15px; border-radius: 4px;
  border: 1px solid var(--border);
  background: var(--bg2); color: var(--text);
  cursor: pointer; font-size: 13px; font-weight: 400;
  letter-spacing: -0.01em;
  transition: all .15s;
}
.btn:hover { border-color: var(--accent); color: var(--accent); }
.btn-primary { background: var(--accent); color: #fff; border-color: var(--accent); }
.btn-primary:hover { background: var(--accent-hover); color: #fff; }
.btn-danger { color: var(--red); border-color: rgba(234,34,97,0.35); }
.btn-danger:hover { background: var(--red); color: #fff; border-color: var(--red); }
.btn-sm { padding: 3px 10px; font-size: 12px; }
.nav-tab {
  padding: 7px 16px; cursor: pointer;
  color: var(--text2); border-radius: 25px;
  font-size: 13px; font-weight: 500; white-space: nowrap;
  letter-spacing: -0.01em;
  transition: all .2s;
}
.nav-tab:hover { color: var(--accent); background: rgba(44,5,116,0.06); }
[data-theme="dark"] .nav-tab:hover { background: rgba(167,139,250,0.12); }
.nav-tab.active { color: #fff; background: var(--accent); font-weight: 600; box-shadow: 0 2px 10px rgba(44,5,116,0.3); }
[data-theme="dark"] .nav-tab.active { color: #1c0738; }
/* ===== Page ===== */
.page { display: none; padding: 26px 30px; max-width: 1060px; }
.page.active { display: block; animation: fadeUp .25s ease; }
@keyframes fadeUp { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }
.page h2 { font-size: 22px; font-weight: 300; letter-spacing: -0.02em; line-height: 1.15; margin-bottom: 18px; }
/* ===== Cards ===== */
.card {
  background: var(--bg2); border-radius: 6px;
  padding: 18px; margin-bottom: 14px;
  border: 1px solid var(--border);
  box-shadow: var(--shadow-sm);
}
.card-title { font-size: 11px; color: var(--text2); margin-bottom: 4px; font-weight: 600; letter-spacing: .08em; text-transform: uppercase; }
.card-value { font-size: 26px; font-weight: 300; letter-spacing: -0.02em; line-height: 1.15; font-feature-settings: 'tnum'; }
/* ===== Stats Grid ===== */
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 14px; margin-bottom: 28px; }
/* ===== Forms ===== */
input, select {
  padding: 10px 14px; border: 1px solid var(--border);
  border-radius: 4px; background: var(--bg2); color: var(--text);
  font-size: 14px; width: 100%; font-family: inherit;
  letter-spacing: -0.01em;
  transition: all .2s;
}
input:focus, select:focus {
  outline: none; border-color: var(--accent2);
  box-shadow: 0 0 0 4px rgba(13,75,188,0.15);
}
.form-group { margin-bottom: 14px; }
.form-group label { display: block; font-size: 12px; color: var(--text2); margin-bottom: 6px; font-weight: 500; letter-spacing: 0; }
.form-row { display: flex; gap: 12px; align-items: flex-end; }
.form-row .form-group { flex: 1; }
/* ===== Tables ===== */
table { width: 100%; border-collapse: collapse; }
th, td { padding: 12px 10px; text-align: left; border-bottom: 1px solid var(--border); font-size: 13px; }
th { color: var(--text2); font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
tbody tr { transition: background .15s; }
tbody tr:hover { background: rgba(44,5,116,0.04); }
[data-theme="dark"] tbody tr:hover { background: rgba(167,139,250,0.08); }
/* ===== Tags ===== */
.tag { display: inline-block; padding: 2px 8px; border-radius: 980px; font-size: 11px; font-weight: 600; letter-spacing: 0; }
.tag-vmess { background: #e8f4ff; color: #0071e3; }
.tag-vless { background: #e3f7ec; color: #1a8f4a; }
.tag-trojan { background: #fff1e5; color: #bd561d; }
.tag-ss { background: #f3e8ff; color: #8250df; }
[data-theme="dark"] .tag-vmess { background: rgba(13,75,188,0.25); color: #7fb0ff; }
[data-theme="dark"] .tag-vless { background: rgba(29,145,89,0.2); color: #4fd183; }
[data-theme="dark"] .tag-trojan { background: rgba(189,86,29,0.2); color: #ffa657; }
[data-theme="dark"] .tag-ss { background: rgba(130,80,223,0.2); color: #d2a8ff; }
/* ===== Status ===== */
.status-active { color: var(--green); }
.status-error { color: var(--red); }
/* ===== Modal ===== */
.modal-overlay {
  display: none; position: fixed; inset: 0;
  background: rgba(0,0,0,0.4);
  backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);
  z-index: 9999; align-items: center; justify-content: center;
}
.modal-overlay.show { display: flex; animation: fadeUp .2s ease; }
.modal-content {
  background: var(--bg2); border-radius: 8px;
  width: 90%; max-width: 700px; max-height: 90vh; overflow: auto;
  box-shadow: 0 20px 60px rgba(0,0,0,0.2);
}
.modal-header { padding: 18px 24px; border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; }
.modal-header h3 { font-size: 17px; font-weight: 600; letter-spacing: -0.02em; }
.modal-body { padding: 24px; }
.modal-close {
  cursor: pointer; font-size: 18px; color: var(--text2);
  background: none; border: none; width: 28px; height: 28px;
  border-radius: 50%; display: flex; align-items: center; justify-content: center;
  transition: all .2s;
}
.modal-close:hover { color: var(--text); background: rgba(0,0,0,0.05); }
/* ===== Sub Items ===== */
.sub-item {
  display: flex; align-items: center; gap: 12px;
  padding: 14px 16px; border-radius: 6px;
  margin-bottom: 8px; cursor: pointer;
  background: var(--bg2); box-shadow: var(--shadow);
  transition: all .2s;
}
.sub-item:hover { transform: translateY(-1px); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
.sub-item .name { font-weight: 600; min-width: 120px; font-size: 13px; }
.sub-item .desc { color: var(--text2); font-size: 12px; min-width: 150px; }
.sub-item input { flex: 1; font-size: 12px; padding: 6px 10px; border: none; border-radius: 4px; background: var(--bg3); color: var(--text); }
/* ===== Login ===== */
.login-page { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; position: relative; overflow: hidden; background: linear-gradient(150deg, #1c1e54 0%, #2e2b8c 55%, #533afd 120%); }
.login-page::before { content:''; position:absolute; width:420px; height:420px; border-radius:50%; background:radial-gradient(circle,#f96bee33,transparent 70%); top:-140px; right:-90px; }
.login-page::after { content:''; position:absolute; width:360px; height:360px; border-radius:50%; background:radial-gradient(circle,#ea226133,transparent 70%); bottom:-130px; left:-70px; }
.login-card {
  position: relative; z-index: 1;
  background: var(--bg2); border-radius: 8px;
  padding: 38px 34px; width: 100%; max-width: 380px;
  box-shadow: var(--shadow-brand); animation: fadeUp .35s ease;
}
.login-card h1 { text-align: center; margin-bottom: 26px; font-size: 24px; font-weight: 300; letter-spacing: -0.02em; }
.login-footer { display: flex; align-items: center; justify-content: center; gap: 8px; margin-top: 22px; font-size: 12px; color: var(--text2); }
.login-footer a, .app-footer a { color: var(--accent); text-decoration: none; }
.login-footer a:hover, .app-footer a:hover { text-decoration: underline; }
.dot { opacity: 0.4; }
.app-footer { border-top: 1px solid var(--border); margin-top: 32px; padding: 16px 4px; font-size: 12px; color: var(--text2); }
/* ===== Upgrade Banner ===== */
.upgrade-banner { display: inline-flex; align-items: center; gap: 6px; padding: 3px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; background: #fff8e1; color: #b45309; }
.upgrade-banner a { color: #b45309; text-decoration: none; }
.upgrade-banner a:hover { text-decoration: underline; }
/* ===== Toast ===== */
.toast { position: fixed; bottom: 24px; right: 24px; z-index: 99999; padding: 12px 20px; border-radius: 14px; color: #fff; font-size: 13px; font-weight: 500; max-width: 360px; animation: fadeIn .3s; box-shadow: 0 8px 30px rgba(0,0,0,0.25); }
.toast-success { background: #1d9159; }
.toast-error { background: #ff3b30; }
/* ===== Rules Tree ===== */
.rules-group { background: var(--bg2); border-radius: 6px; margin-bottom: 8px; border: 1px solid var(--border); box-shadow: var(--shadow-sm); overflow: hidden; }
.rules-loading { padding: 40px 20px; text-align: center; color: var(--text2); }
.rules-group-head { display: flex; align-items: center; gap: 10px; padding: 14px 16px; cursor: pointer; user-select: none; transition: background .2s; }
.rules-group-head:hover { background: rgba(0,0,0,0.03); }
[data-theme="dark"] .rules-group-head:hover { background: rgba(255,255,255,0.04); }
.rules-arrow { display: inline-flex; transition: transform .25s ease; color: var(--text2); font-size: 12px; width: 14px; justify-content: center; }
.rules-group-head.open .rules-arrow { transform: rotate(90deg); }
.rules-group-title { font-weight: 600; font-size: 15px; flex: 1; }
.rules-group-count { font-size: 12px; color: var(--text2); background: rgba(0,0,0,0.05); padding: 2px 10px; border-radius: 999px; }
[data-theme="dark"] .rules-group-count { background: rgba(255,255,255,0.1); }
.rules-items { display: none; padding: 6px 20px 16px 48px; gap: 8px 14px; }
.rules-group-head.open + .rules-items { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }
.rules-item {
  display: grid;
  grid-template-columns: 20px 1fr;
  align-items: center;
  gap: 9px;
  padding: 9px 12px; border-radius: 10px;
  cursor: pointer; font-size: 13px;
  min-width: 0; line-height: 1.3;
  height: 48px;
}
.rules-item .rule-label {
  display: grid;
  gap: 2px;
  min-width: 0;
}
.rules-item .rule-name {
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.rules-item .rule-id {
  font-size: 11px; color: var(--text2);
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.rules-group-head input[type="checkbox"] { accent-color: var(--accent); cursor: pointer; width: 16px; height: 16px; }
/* ===== Catalog Type Filter Chips ===== */
.catalog-chip {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 6px 14px; border-radius: 980px;
  border: 1px solid var(--border); background: var(--bg2);
  color: var(--text2); font-size: 13px; font-weight: 500;
  cursor: pointer; transition: all .2s;
}
.catalog-chip:hover { background: var(--bg3); }
.catalog-chip.active { background: var(--accent); color: #fff; border-color: var(--accent); }
.catalog-chip-count { font-size: 11px; background: rgba(0,0,0,0.08); padding: 1px 7px; border-radius: 999px; }
.catalog-chip.active .catalog-chip-count { background: rgba(255,255,255,0.22); }
/* ===== Scroll to Top ===== */
.scroll-top { position: fixed; bottom: 60px; right: 20px; z-index: 999; width: 44px; height: 44px; border-radius: 50%; background: var(--accent); color: #fff; border: none; cursor: pointer; font-size: 18px; display: none; box-shadow: var(--shadow-sm); }
.scroll-top.show { display: flex; align-items: center; justify-content: center; }
/* ===== Helpers ===== */
.text-center { text-align: center; }
.mt-12 { margin-top: 12px; }
.mb-12 { margin-bottom: 12px; }
.gap-8 { gap: 8px; }
.flex { display: flex; }
.flex-wrap { flex-wrap: wrap; }
.items-center { align-items: center; }
/* ===== Responsive ===== */
@media (max-width: 900px) {
  .app-shell { flex-direction: column; }
  .sidebar { width: 100%; height: auto; position: static; flex-direction: row; align-items: center; overflow-x: auto; padding: 10px 14px; gap: 4px; }
  .sidebar .logo { padding: 0 8px 0 0; white-space: nowrap; }
  .sgroup { display: none; }
  .nav-tab { white-space: nowrap; }
  .sidebar-footer { margin-top: 0; margin-left: auto; padding-top: 0; }
  .page { padding: 20px 14px; }
  .stats-grid { grid-template-columns: 1fr 1fr; gap: 10px; }
  .sub-item { flex-wrap: wrap; padding: 12px; }
  .sub-item input { min-width: 100%; }
  .sub-item .name { min-width: 100%; }
  .form-row { flex-direction: column; }
}
</style>
</head>
<body>
<div id="app" style="display:none">
  <div class="app-shell">
    <aside class="sidebar">
      <div class="logo" id="sidebarLogo">◆ SUB<span>Next</span></div>
      <div class="sgroup">总览</div>
      <div class="nav-tab active" data-page="dashboard" onclick="switchPage('dashboard')">📊 仪表盘</div>
      <div class="sgroup">资源</div>
      <div class="nav-tab" data-page="subscribe" onclick="switchPage('subscribe')">📥 订阅管理</div>
      <div class="nav-tab" data-page="nodes" onclick="switchPage('nodes')">🔗 节点列表</div>
      <div class="nav-tab" data-page="rules" onclick="switchPage('rules')">🌐 分流规则</div>
      <div class="sgroup">发布</div>
      <div class="nav-tab" data-page="output" onclick="switchPage('output')">📦 输出配置</div>
      <div class="nav-tab" data-page="settings" onclick="switchPage('settings')">⚙️ 设置</div>
      <div class="sidebar-footer">
        <button class="btn btn-sm" onclick="cycleTheme()" id="themeBtn">🌙</button>
        <span id="userBadge" style="font-size:12.5px;color:var(--text2)">admin</span>
        <button class="btn btn-sm" onclick="logout()">🚪 退出</button>
      </div>
    </aside>
    <div class="main-col">

  <!-- Dashboard -->
  <div class="page active" id="page-dashboard">
    <h2 style="margin-bottom:16px">📊 仪表盘</h2>
    <div class="stats-grid" id="statsGrid">
      <div class="card"><div class="card-title">订阅数量</div><div class="card-value" id="statSubs">-</div></div>
      <div class="card"><div class="card-title">节点总数</div><div class="card-value" id="statNodes">-</div></div>
      <div class="card"><div class="card-title">已启用节点</div><div class="card-value" id="statEnabled">-</div></div>
      <div class="card"><div class="card-title">已禁用节点</div><div class="card-value" id="statDisabled">-</div></div>
      <div class="card"><div class="card-title">协议分布</div><div class="card-value" style="font-size:13px" id="statProto">-</div></div>
      <div class="card"><div class="card-title">最近更新</div><div class="card-value" style="font-size:14px" id="statUpdate">-</div></div>
    </div>
  </div>

  <!-- Subscriptions -->
  <div class="page" id="page-subscribe">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
      <h2>📥 订阅管理</h2>
      <button class="btn btn-primary" onclick="showAddSub()">＋ 添加订阅</button>
    </div>
    <table id="subTable">
      <thead><tr><th>名称</th><th>状态</th><th>节点数</th><th>更新时间</th><th>操作</th></tr></thead>
      <tbody id="subTableBody"></tbody>
    </table>
  </div>

  <!-- Nodes -->
  <div class="page" id="page-nodes">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
      <h2>🔗 节点列表</h2>
      <input style="width:auto;max-width:300px" placeholder="🔍 搜索节点名或地址..." id="nodeSearch" oninput="filterNodes()">
    </div>
    <div class="card" style="padding:12px 16px;font-size:13px;color:var(--text2)">
      💡 勾选 = 该节点会进入输出配置；取消勾选 = 从输出的订阅中排除。测速请在客户端（OpenClash/Mihomo 等）导入订阅后测试。
    </div>
    <div class="card" id="nodeStats" style="margin:12px 0;padding:10px 16px;display:flex;gap:24px;font-size:13px">
      <span>📥 总节点 <b id="statsOriginal">0</b></span>
      <span>🔀 重复 <b id="statsDuplicates">0</b></span>
      <span>✅ 实际 <b id="statsUnique">0</b></span>
      <span style="color:var(--text2)">（去重依据：IP + 端口 + 协议）</span>
    </div>
    <div class="card" style="margin:0 0 12px;padding:10px 16px;display:flex;gap:8px;flex-wrap:wrap;align-items:center">
      <label style="font-size:13px;font-weight:500">🧹 节点名清洗</label>
      <input id="cleanPattern" placeholder="输入要删除的片段，如 地区随机_|_" style="width:auto;flex:1;min-width:200px">
      <label style="font-size:12px;color:var(--text2);display:flex;align-items:center;gap:4px"><input type="checkbox" id="cleanRegex"> 正则模式</label>
      <button class="btn btn-sm" onclick="previewClean()">👁️ 预览</button>
      <button class="btn btn-sm btn-primary" onclick="applyClean()">🧹 清洗</button>
    </div>
    <div class="card" id="cleanPreviewBox" style="display:none;margin:0 0 12px;padding:10px 16px;font-size:13px"></div>
    <table id="nodesTable">
      <thead><tr><th style="width:40px"><input type="checkbox" id="nodeSelectAll" onchange="toggleSelectAll(this)" checked></th><th>名称</th><th>协议</th><th>地址</th><th>端口</th><th>TLS</th><th>操作</th></tr></thead>
      <tbody id="nodesTableBody"></tbody>
    </table>
    <p class="text-center" id="nodesEmpty" style="color:var(--text2);padding:24px">暂无节点数据</p>
  </div>

  <!-- Rules -->
  <div class="page" id="page-rules">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
      <h2>🌐 分流规则</h2>
      <span style="font-size:13px;color:var(--text2)">已选 <b id="rulesCount" style="color:var(--accent)">0</b> 条规则</span>
    </div>
    <div class="card" style="padding:12px 16px;font-size:13px;color:var(--text2)">
      💡 勾选 MetaCubeX 规则集，生成订阅时自动写入对应分流规则。点击大类标题展开子项，可直接勾选整个大类，也可单独勾选其中几项。
    </div>
    <div class="card" style="padding:12px 16px;margin-bottom:12px">
      <div style="font-size:13px;font-weight:500;margin-bottom:8px">⚡ 快速预设 <span style="color:var(--text2);font-weight:normal;font-size:12px">点击覆盖当前勾选，配置跟随输出</span></div>
      <div style="display:flex;gap:8px;flex-wrap:wrap" id="presetBar"></div>
    </div>
    <div style="display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:16px;align-items:start" id="rulesTwoCol">
      <div>
        <div id="rulesTree"></div>
        <div style="margin-top:12px;display:flex;gap:8px">
          <button class="btn btn-primary" onclick="selectAllRules(true)">✅ 全选</button>
          <button class="btn" onclick="selectAllRules(false)">⬜ 全不选</button>
          <button class="btn" onclick="resetRulesExpanded()">🔽 全部展开</button>
        </div>
      </div>

      <!-- 规则库：从 MetaCubeX 全量分类挑选加入分流规则 + 同步管理（右侧栏） -->
      <div class="card" style="position:sticky;top:16px">
      <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;margin-bottom:12px">
        <h3 style="margin:0">📚 规则库 <span style="color:var(--text2);font-size:12px;font-weight:normal">从 1546 个 MetaCubeX 分类中挑选加入分流规则</span></h3>
        <div style="display:flex;align-items:center;gap:12px">
          <span style="color:var(--text2);font-size:12px" id="catalogCount"></span>
          <button class="btn btn-sm" onclick="refreshCatalog()" id="catalogRefreshBtn">🔄 立即刷新</button>
        </div>
      </div>
      <!-- 同步状态 / 失效历史（展开式） -->
      <div id="catalogStatus" style="color:var(--text2);font-size:12px;padding:6px 12px;background:var(--bg);border-radius:8px;margin-bottom:12px">加载中…</div>
      <div id="catalogRemovedSection" style="display:none;margin-bottom:12px">
        <div style="display:flex;align-items:center;gap:8px;cursor:pointer" onclick="toggleRemovedHistory()">
          <span id="catalogRemovedToggle">▶</span>
          <span style="font-size:12px;color:var(--text2)">失效分类历史 (<span id="catalogRemovedCount">0</span>)</span>
        </div>
        <div id="catalogRemovedList" style="display:none;margin-top:8px;max-height:200px;overflow-y:auto;border:1px solid var(--border);border-radius:12px;padding:8px;font-size:13px"></div>
      </div>
      <!-- 分类筛选 chips（方案 A：缩小范围再挑，避免平铺几千条） -->
      <div id="catalogTypeFilter" style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px">
        <button class="catalog-chip active" data-type="" onclick="setCatalogType(this)">全部</button>
        <button class="catalog-chip" data-type="aggregate" onclick="setCatalogType(this)">🎯 聚合 <span class="catalog-chip-count" data-count="aggregate">0</span></button>
        <button class="catalog-chip" data-type="site" onclick="setCatalogType(this)">🌐 站点 <span class="catalog-chip-count" data-count="site">0</span></button>
      </div>
      <div class="form-group">
        <input id="catalogSearch" placeholder="🔍 输入分类名或搜索（如 netflix、openai、ads）…" oninput="debouncedSearchCatalog()">
      </div>
      <div id="catalogList" style="max-height:420px;overflow-y:auto;border:1px solid var(--border);border-radius:12px;padding:8px">
        <div style="color:var(--text2);padding:16px;text-align:center">输入关键词开始搜索</div>
      </div>
      </div><!-- /规则库右栏 -->
    </div><!-- /rulesTwoCol -->
  </div>

  <!-- Output -->
  <div class="page" id="page-output">
    <!-- 格式选择器 + 主操作（A：提到主流程） -->
    <div class="card" style="display:flex;flex-wrap:wrap;align-items:flex-end;gap:12px;margin-bottom:16px">
      <div style="flex:1;min-width:220px">
        <label for="outputFormatSelect" style="display:block;font-size:12px;color:var(--text2);margin-bottom:6px;font-weight:500">选择客户端格式</label>
        <select id="outputFormatSelect" onchange="onOutputFormatChange()">
          <option value="mihomo">🐱 Mihomo / Clash / Stash</option>
          <option value="singbox">📦 Sing-box</option>
          <option value="v2ray">📄 V2ray (Base64)</option>
          <option value="v2rayn">📱 V2RayNG</option>
          <option value="nekoray">🪐 NekoRay</option>
          <option value="shadowrocket">🚀 Shadowrocket</option>
          <option value="loon">🌙 Loon</option>
          <option value="surge">⚡ Surge</option>
          <option value="quantumultx">🍁 Quantumult X</option>
        </select>
      </div>
      <div style="display:flex;gap:8px;flex-wrap:wrap">
        <button class="btn btn-primary" onclick="copyOutputFormatUrl()">📋 复制订阅链接</button>
        <button class="btn btn-primary" onclick="downloadOutputFormat()">💾 下载配置文件</button>
        <button class="btn" onclick="showQrOutputFormat()">📱 二维码</button>
        <button class="btn" onclick="previewOutputFormat()">👁️ 预览配置</button>
      </div>
    </div>
    <div id="outputNodeCount" style="font-size:13px;color:var(--text2);margin-bottom:16px">0 个节点</div>
    <div id="outputLinks"></div>
  </div>

  <!-- Settings -->
  <div class="page" id="page-settings">
    <h2 style="margin-bottom:16px">⚙️ 设置</h2>
    <div class="card">
      <div class="form-group">
        <label>系统名称</label>
        <input id="settingAppName" placeholder="CF-Workers-SUB-Next">
      </div>
      <button class="btn btn-primary mt-12" onclick="saveSettings()">💾 保存</button>
    </div>
    <div class="card" style="margin-top:16px">
      <h3 style="margin:0 0 12px">👤 账号安全</h3>
      <div class="form-group">
        <label>当前用户名：<b id="currentUsername" style="color:var(--accent)">-</b></label>
        <label style="margin-top:8px">新用户名（2-32位字母数字_-）</label>
        <input id="settingNewUsername" placeholder="新用户名" autocomplete="off">
        <label style="margin-top:8px">当前密码（确认）</label>
        <input type="password" id="settingUsernamePassword" autocomplete="current-password">
      </div>
      <button class="btn btn-primary" onclick="changeUsername()">修改用户名</button>
    </div>
    <div class="card" style="margin-top:16px">
      <h3 style="margin:0 0 12px">🔑 修改密码</h3>
      <div class="form-group">
        <label>旧密码</label>
        <input type="password" id="settingOldPassword" autocomplete="current-password">
        <label style="margin-top:8px">新密码（至少6位）</label>
        <input type="password" id="settingNewPassword" autocomplete="new-password">
        <label style="margin-top:8px">确认新密码</label>
        <input type="password" id="settingNewPassword2" autocomplete="new-password">
      </div>
      <button class="btn btn-primary" onclick="changePassword()">修改密码</button>
      <p class="mt-12" style="color:var(--text2);font-size:12px">修改成功后需重新登录。</p>
    </div>
  </div>

  <!-- 加入规则弹窗 -->
  <div class="modal-overlay" id="addRuleModal">
    <div class="modal-content" style="max-width:480px">
      <div class="modal-header"><h3>➕ 加入分流规则</h3><button class="modal-close" onclick="closeModal('addRuleModal')">✕</button></div>
      <div class="modal-body">
        <div class="form-group"><label>分类 ID</label><input id="addRuleId" readonly></div>
        <div class="form-group"><label>显示名称</label><input id="addRuleLabel" placeholder="例如: Netfilx"></div>
        <div class="form-group">
          <label>目标分组</label>
          <select id="addRuleGroup"></select>
        </div>
        <button class="btn btn-primary" style="width:100%;justify-content:center" onclick="confirmAddRule()">✅ 加入规则</button>
      </div>
    </div>
  </div>

  <!-- 全局页脚（项目信息 + 升级检测） -->
  <footer class="app-footer">
    <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
      <span>🔐 CF-Workers-SUB-Next <span class="dot">·</span> v<span id="appVersion">-</span></span>
      <span class="dot">·</span>
      <a href="https://github.com/bobvane/CF-Workers-SUB-Next" target="_blank" rel="noopener">GitHub</a>
      <span class="dot">·</span>
      <span id="upgradeStatus"></span>
    </div>
  </footer>
    </div><!-- /main-col -->
  </div><!-- /app-shell -->
</div>

<!-- Login -->
<div class="login-page" id="loginPage" style="display:none">
  <div class="login-card">
    <h1 id="loginTitle">🔐 CF-Workers-SUB-Next</h1>
    <div class="form-group">
      <label>用户名</label>
      <input id="loginUsername" placeholder="admin" autocomplete="username">
    </div>
    <div class="form-group">
      <label>管理员密码</label>
      <input type="password" id="loginPassword" placeholder="输入密码" autocomplete="current-password" onkeydown="if(event.key==='Enter')login()">
    </div>
    <button class="btn btn-primary" style="width:100%;justify-content:center" onclick="login()">登录</button>
    <p class="text-center mt-12" style="color:var(--text2);font-size:12px">首次登录使用 ADMIN_PASSWORD 环境变量设置的密码</p>
    <!-- 项目品牌信息 -->
    <div class="login-footer">
      <a href="https://github.com/bobvane/CF-Workers-SUB-Next" target="_blank" rel="noopener">⭐ GitHub</a>
      <span class="dot">·</span>
      <span>v<span id="loginVersion">-</span></span>
      <span class="dot">·</span>
      <span>by Bob Vane</span>
    </div>
  </div>
</div>

<!-- Add Subscription Modal -->
<div class="modal-overlay" id="addSubModal">
  <div class="modal-content">
    <div class="modal-header"><h3>添加订阅</h3><button class="modal-close" onclick="closeModal('addSubModal')">✕</button></div>
    <div class="modal-body">
      <div class="form-group"><label>名称</label><input id="subName" placeholder="例如: My Airport"></div>
      <div class="form-group"><label>订阅 URL</label><input id="subUrl" placeholder="https://example.com/sub"></div>
      <button class="btn btn-primary" onclick="addSub()">➕ 添加</button>
    </div>
  </div>
</div>

<!-- Config Preview Modal -->
<div class="modal-overlay" id="configModal">
  <div class="modal-content" style="max-width:800px">
    <div class="modal-header"><h3>📄 配置预览</h3><button class="modal-close" onclick="closeModal('configModal')">✕</button></div>
    <div class="modal-body">
      <div style="margin-bottom:12px">
        <label style="font-size:13px;color:var(--text2)">选择格式：</label>
        <select id="previewFormatSelect" onchange="previewSelect()" style="max-width:260px">
          <option value="mihomo">🐱 Mihomo / Clash / Stash</option>
          <option value="singbox">📦 Sing-box</option>
          <option value="v2ray">📄 V2ray (Base64)</option>
          <option value="v2rayn">📱 V2RayNG</option>
          <option value="nekoray">🪐 NekoRay</option>
          <option value="shadowrocket">🚀 Shadowrocket</option>
          <option value="loon">🌙 Loon</option>
          <option value="surge">⚡ Surge</option>
          <option value="quantumultx">🍁 Quantumult X</option>
        </select>
        <button class="btn btn-primary btn-sm" onclick="previewSelect(true)" style="margin-left:8px">👉 加载</button>
        <button class="btn btn-sm" onclick="downloadConfigByFormat()" style="margin-left:8px">💾 下载配置文件</button>
      </div>
      <pre id="configPreview" style="background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:12px;font-size:12px;overflow:auto;max-height:60vh;white-space:pre-wrap;word-break:break-all">选择格式查看预览</pre>
    </div>
  </div>
</div>

<!-- QR 码 Modal -->
<div class="modal-overlay" id="qrModal">
  <div class="modal-content" style="max-width:380px;text-align:center">
    <div class="modal-header"><h3>📱 扫码订阅</h3><button class="modal-close" onclick="closeModal('qrModal')">✕</button></div>
    <div class="modal-body">
      <div id="qrContainer" style="display:inline-block;background:#fff;padding:16px;border-radius:12px;margin:8px 0"></div>
      <p id="qrFormatName" style="margin:8px 0 4px;font-weight:600"></p>
      <p style="font-size:12px;color:var(--text2)">用代理客户端扫描此码导入订阅</p>
    </div>
  </div>
</div>

<script>
// ============ State ============
let state = { subscriptions: [], nodes: [], currentPage: 'dashboard', authenticated: false };

// ============ Theme ============
const themes = ['light', 'dark'];
let themeIdx = 0;
function applyTheme(t) {
  document.documentElement.dataset.theme = t;
  document.getElementById('themeBtn').textContent = t === 'dark' ? '☀️' : '🌙';
  try { localStorage.setItem('subnext-theme', t); } catch (e) {}
}
function cycleTheme() {
  themeIdx = (themeIdx + 1) % themes.length;
  applyTheme(themes[themeIdx]);
}
(function initTheme() {
  let saved = null;
  try { saved = localStorage.getItem('subnext-theme'); } catch (e) {}
  if (!saved && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) saved = 'dark';
  if (saved === 'dark') { themeIdx = 1; }
  applyTheme(saved || themes[themeIdx]);
})();

// ============ Toast ============
function toast(msg, type = 'success') {
  const el = document.createElement('div');
  el.className = \`toast toast-\${type}\`;
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => el.remove(), 3000);
}

// ============ Modal ============
function showModal(id) { document.getElementById(id).classList.add('show'); }
function closeModal(id) { document.getElementById(id).classList.remove('show'); }
document.addEventListener('click', function(e) {
  if (e.target.classList.contains('modal-overlay')) e.target.classList.remove('show');
});

// ============ API ============
async function api(path, options = {}) {
  const urlParams = new URLSearchParams(window.location.search);
  const token = urlParams.get('token');
  const sep = path.includes('?') ? '&' : '?';
  const url = '/api' + path + (token ? \`\${sep}token=\${token}\` : '');
  const res = await fetch(url, { method: 'GET', headers: { 'Content-Type': 'application/json' }, credentials: 'include', ...options });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error?.message || 'Request failed');
  return data;
}

// ============ Auth ============
async function checkSession() {
  try {
    const data = await api('/auth/session');
    if (data.data?.authenticated) {
      state.authenticated = true;
      document.getElementById('loginPage').style.display = 'none';
      document.getElementById('app').style.display = 'block';
      // 刷新页面恢复会话时，同步右上角用户名
      try {
        const u = await api('/auth/username');
        const badge = document.getElementById('userBadge');
        if (badge && u.data?.username) badge.textContent = u.data.username;
      } catch {}
      loadDashboard();
      return true;
    }
  } catch {}
  state.authenticated = false;
  document.getElementById('loginPage').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
  return false;
}

async function login() {
  const username = document.getElementById('loginUsername').value.trim() || 'admin';
  const password = document.getElementById('loginPassword').value;
  if (!password) { toast('请输入密码', 'error'); return; }
  try {
    await api('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) });
    document.getElementById('loginPassword').value = '';
    toast('登录成功');
    // 右上角用户徽标显示实际登录用户名
    const badge = document.getElementById('userBadge');
    if (badge) badge.textContent = username;
    state.authenticated = true;
    document.getElementById('loginPage').style.display = 'none';
    document.getElementById('app').style.display = 'block';
    loadDashboard();
  } catch (e) {
    toast('密码错误: ' + e.message, 'error');
  }
}

async function logout() {
  try { await api('/auth/logout', { method: 'POST' }); } catch {}
  state.authenticated = false;
  document.getElementById('loginPage').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
}

// ============ Page Switching ============
function switchPage(page) {
  state.currentPage = page;
  document.querySelectorAll('.nav-tab').forEach(t => t.classList.toggle('active', t.dataset.page === page));
  document.querySelectorAll('.page').forEach(p => p.classList.toggle('active', p.id === 'page-' + page));
  window.location.hash = page;
  // 未登录时不加载任何数据（避免 401 toast）
  if (!state.authenticated) return;
  if (page === 'dashboard') loadDashboard();
  if (page === 'subscribe') loadSubscriptions();
  if (page === 'nodes') loadNodes();
  if (page === 'output') loadOutput();
  if (page === 'rules') { loadRules(); ensureCatalogLoaded(); }
  if (page === 'settings') { loadSettings(); loadCurrentUsername(); }
}

// ============ 分流规则 ============
// 规则大类数据由后端 /api/rules/groups 提供（来源：src/data/metacubex-rules.ts）
let RULE_GROUPS = [];
// 每个规则默认勾选状态（1 全部选中，0 未选）
let ruleSelected = {};
let ruleExpanded = {};

function initRuleState() {
  ruleSelected = {};
  ruleExpanded = {};
  RULE_GROUPS.forEach(g => {
    g.items.forEach(it => { ruleSelected[it.id] = false; });  // 默认不勾选（由后端保存的选择决定）
    ruleExpanded[g.key] = false;  // 默认折叠
  });
}

function renderRulesTree() {
  const container = document.getElementById('rulesTree');
  container.innerHTML = RULE_GROUPS.map((g, gi) => {
    const allChecked = g.items.every(it => ruleSelected[it.id]);
    const checkedCount = g.items.filter(it => ruleSelected[it.id]).length;
    const cls = ruleExpanded[g.key] ? 'open' : '';
    // 大类 checkbox：全选时打勾，部分选时半选（CSS 用 indeterminate）
    const itemsHTML = g.items.map(it => {
      const isCustom = window._customRules && window._customRules.includes(it.id);
      return \`<label class="rules-item">
        <input type="checkbox" data-rule-check data-g="\${gi}" data-id="\${it.id}" \${ruleSelected[it.id] ? 'checked' : ''} onchange="onRuleItemChange(this)">
        <span class="rule-label"><span class="rule-name">\${it.label}</span><span class="rule-id">\${it.tag}:\${it.id}</span></span>
        \${isCustom ? \`<span style="cursor:pointer;color:var(--red);font-size:14px;margin-left:4px" onclick="event.stopPropagation();deleteCustomRule('\${it.id}')" title="删除此规则">✕</span>\` : ''}
      </label>\`;
    }).join('');
    return \`
      <div class="rules-group">
        <div class="rules-group-head \${cls}" data-g="\${gi}" onclick="toggleRuleGroup(\${gi})">
          <span class="rules-arrow">▶</span>
          <input type="checkbox" data-group-check data-g="\${gi}" \${allChecked ? 'checked' : ''} onclick="event.stopPropagation()" onchange="onRuleGroupChange(this)">
          <span class="rules-group-title">\${g.icon || ''} \${g.name}</span>
          <span class="rules-group-count">\${checkedCount} / \${g.items.length}</span>
        </div>
        <div class="rules-items">\${itemsHTML}</div>
      </div>\`;
  }).join('');
  // 设置半选状态
  RULE_GROUPS.forEach((g, gi) => {
    const cb = document.querySelector(\`.rules-group-head[data-g="\${gi}"] input[data-group-check]\`);
    if (cb) cb.indeterminate = g.items.some(it => ruleSelected[it.id]) && !g.items.every(it => ruleSelected[it.id]);
  });
  updateRulesCount();
  renderPresetBar();
}

function toggleRuleGroup(gi) {
  ruleExpanded[RULE_GROUPS[gi].key] = !ruleExpanded[RULE_GROUPS[gi].key];
  renderRulesTree();
}

function onRuleGroupChange(cb) {
  const gi = +cb.dataset.g;
  const checked = cb.checked;
  RULE_GROUPS[gi].items.forEach(it => { ruleSelected[it.id] = checked; });
  renderRulesTree();
  saveRuleSelection();
}

function onRuleItemChange(cb) {
  const gi = +cb.dataset.g;
  const id = cb.dataset.id;
  ruleSelected[id] = cb.checked;
  renderRulesTree();
  saveRuleSelection();
}

function updateRulesCount() {
  const total = Object.values(ruleSelected).filter(Boolean).length;
  document.getElementById('rulesCount').textContent = total;
}

// 把当前勾选的规则 id 保存到后端
function saveRuleSelection() {
  const ids = RULE_GROUPS.flatMap(g => g.items).filter(it => ruleSelected[it.id]).map(it => it.id);
  fetch('/api/rules/selection', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ids }),
  }).then(r => r.json()).then(() => {}).catch(() => toast('规则保存失败', 'error'));
}

function selectAllRules(check) {
  RULE_GROUPS.forEach(g => g.items.forEach(it => { ruleSelected[it.id] = check; }));
  renderRulesTree();
  saveRuleSelection();
}

// ============ 快速预设 ============
// 以"组"为单位：选中组全组勾选，未选组全组取消；组内规则目标配置不变
const RULE_PRESETS = [
  { key: 'mini', label: '🟢 极简', groups: ['ads','china-direct','china-media','netease','media','ai'] },
  { key: 'mini-crypto', label: '🟢 极简+加密', groups: ['ads','china-direct','china-media','netease','media','ai','crypto'] },
  { key: 'standard', label: '🔵 标准', groups: ['ads','china-direct','china-media','netease','media','ai','google-fcm','bing','onedrive','microsoft','apple','game'] },
  { key: 'standard-crypto', label: '🔵 标准+加密', groups: ['ads','china-direct','china-media','netease','media','ai','google-fcm','bing','onedrive','microsoft','apple','game','crypto'] },
  { key: 'full', label: '🟣 完全体', groups: null },  // null = 除 crypto 外全部
  { key: 'full-crypto', label: '🟣 完全+加密', groups: 'ALL' },
];

function presetGroups(p) {
  if (p.groups === 'ALL') return RULE_GROUPS.map(g => g.key);
  if (p.groups === null) return RULE_GROUPS.filter(g => g.key !== 'crypto').map(g => g.key);
  return p.groups;
}

function applyPreset(key) {
  const p = RULE_PRESETS.find(x => x.key === key);
  if (!p) return;
  const on = new Set(presetGroups(p));
  RULE_GROUPS.forEach(g => {
    const checked = on.has(g.key);
    g.items.forEach(it => {
      // 只动本分组预置项；用户自定义加入的规则（custom）跟随其所在组的开关
      ruleSelected[it.id] = checked;
    });
  });
  renderRulesTree();
  saveRuleSelection();
  toast(\`已应用预设「\${p.label.replace(/^\S+\s/, '')}」\`);
}

// 当前勾选状态与某预设完全一致时高亮；用户手动改动后自然失配
function activePresetKey() {
  for (const p of RULE_PRESETS) {
    const keys = new Set(presetGroups(p));
    let match = true;
    for (const g of RULE_GROUPS) {
      const want = keys.has(g.key);
      for (const it of g.items) {
        if (ruleSelected[it.id] !== want) { match = false; break; }
      }
      if (!match) break;
    }
    if (match) return p.key;
  }
  return null;  // 自定义状态，无高亮
}

function renderPresetBar() {
  const bar = document.getElementById('presetBar');
  if (!bar || RULE_GROUPS.length === 0) return;
  const act = activePresetKey();
  bar.innerHTML = RULE_PRESETS.map(p =>
    \`<button class="btn btn-sm \${p.key === act ? 'btn-primary' : ''}" onclick="applyPreset('\${p.key}')">\${p.label}</button>\`
  ).join('');
}

function resetRulesExpanded() {
  RULE_GROUPS.forEach(g => { ruleExpanded[g.key] = true; });
  renderRulesTree();
}

function loadRules() {
  // 首次加载时从后端拉取规则大类 + 已保存的选择 + 自定义规则，同时显示加载状态
  const container = document.getElementById('rulesTree');
  if (RULE_GROUPS.length === 0) {
    container.innerHTML = '<div class="rules-loading">⏳ 正在加载规则…</div>';
    Promise.all([
      fetch('/api/rules/groups').then(r => r.json()),
      fetch('/api/rules/selection').then(r => r.json()),
      fetch('/api/rules/custom').then(r => r.json()),
    ])
      .then(([groupsRes, selRes, customRes]) => {
        if (groupsRes.success && groupsRes.data && groupsRes.data.groups) {
          RULE_GROUPS = groupsRes.data.groups;
          window._customRules = (customRes.data?.rules || []).map(r => r.id);
          initRuleState();
          // 应用已保存的选择
          if (selRes.success && selRes.data && Array.isArray(selRes.data.ids)) {
            selRes.data.ids.forEach(id => { if (id in ruleSelected) ruleSelected[id] = true; });
          }
          renderRulesTree();
        } else {
          container.innerHTML = '<div class="rules-loading" style="color:var(--red)">❌ 规则数据加载失败</div>';
        }
      })
      .catch(() => {
        container.innerHTML = '<div class="rules-loading" style="color:var(--red)">❌ 规则数据加载失败</div>';
      });
  } else {
    renderRulesTree();
  }
}

// ============ Dashboard ============
async function loadDashboard() {
  try {
    const data = await api('/dashboard');
    document.getElementById('statSubs').textContent = data.data.subscriptions;
    document.getElementById('statNodes').textContent = data.data.nodes;
    document.getElementById('statEnabled').textContent = data.data.enabledNodes ?? '-';
    document.getElementById('statDisabled').textContent = data.data.disabledNodes ?? '-';
    // 协议分布
    const proto = data.data.protoCount || {};
    const protoNames = { vmess:'VMess', vless:'VLESS', trojan:'Trojan', shadowsocks:'SS', ss:'SS' };
    const protoStr = Object.entries(proto)
      .map(([k,v]) => (protoNames[k] || k) + ': ' + v)
      .join(' · ');
    document.getElementById('statProto').textContent = protoStr || '-';
    // 最近更新时间
    document.getElementById('statUpdate').textContent = data.data.lastUpdate ? new Date(data.data.lastUpdate).toLocaleString() : '暂无';
  } catch { toast('加载仪表盘失败', 'error'); }
}

// ============ Subscriptions ============
async function loadSubscriptions() {
  try {
    const data = await api('/subscriptions');
    state.subscriptions = data.data || [];
    renderSubTable();
  } catch { toast('加载订阅失败', 'error'); }
}

function renderSubTable() {
  const tbody = document.getElementById('subTableBody');
  if (state.subscriptions.length === 0) {
    tbody.innerHTML = '<tr><td colspan="5" class="text-center" style="color:var(--text2);padding:24px">暂无订阅，点击右上角添加</td></tr>';
    return;
  }
  tbody.innerHTML = state.subscriptions.map(s => \`
    <tr>
      <td><strong>\${escHtml(s.name)}</strong></td>
      <td><span class="status-\${s.status}">\${s.status === 'active' ? '✅ 正常' : s.status === 'error' ? '❌ 错误' : '⏸ 停用'}</span></td>
      <td>\${s.nodeCount ?? 0}</td>
      <td style="font-size:12px;color:var(--text2)">\${s.updatedAt ? new Date(s.updatedAt).toLocaleString() : '-'}</td>
      <td>
        <button class="btn btn-sm" onclick="updateSub('\${s.id}')">🔄 更新</button>
        <button class="btn btn-sm btn-danger" onclick="deleteSub('\${s.id}')">🗑 删除</button>
      </td>
    </tr>
  \`).join('');
}

function showAddSub() { showModal('addSubModal'); }

async function addSub() {
  const name = document.getElementById('subName').value.trim();
  const url = document.getElementById('subUrl').value.trim();
  if (!name || !url) { toast('请填写名称和 URL', 'error'); return; }
  try {
    const data = await api('/subscriptions', { method: 'POST', body: JSON.stringify({ name, url }) });
    toast('添加成功');
    document.getElementById('subName').value = '';
    document.getElementById('subUrl').value = '';
    closeModal('addSubModal');
    // 乐观更新：立即把新订阅插进列表（避免 KV 最终一致性的读取延迟）
    state.subscriptions.unshift({
      id: data.data.id,
      name: name,
      status: 'active',
      nodeCount: 0,
      updatedAt: Date.now(),
    });
    renderSubTable();
    // 后台再拉一次，确保拿到服务器最新数据（含其他字段）
    setTimeout(loadSubscriptions, 800);
  } catch (e) { toast('添加失败: ' + e.message, 'error'); }
}

async function updateSub(id) {
  try {
    await api('/subscriptions/' + id + '/update', { method: 'POST' });
    toast('更新成功');
    loadSubscriptions();
  } catch (e) { toast('更新失败: ' + e.message, 'error'); }
}

async function deleteSub(id) {
  if (!confirm('确定删除此订阅？')) return;
  try {
    await api('/subscriptions/' + id, { method: 'DELETE' });
    toast('删除成功');
    loadSubscriptions();
  } catch (e) { toast('删除失败: ' + e.message, 'error'); }
}

// ============ Nodes ============
async function loadNodes() {
  try {
    const res = await api('/nodes');
    state.nodes = res.data || [];
    // 显示去重统计
    if (res.stats) {
      const setStat = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = String(v ?? 0); };
      setStat('statsOriginal', res.stats.original);
      setStat('statsDuplicates', res.stats.duplicates);
      setStat('statsUnique', res.stats.unique);
    }
    renderNodes();
  } catch { toast('加载节点失败', 'error'); }
}

function renderNodes() {
  const tbody = document.getElementById('nodesTableBody');
  const empty = document.getElementById('nodesEmpty');
  const search = document.getElementById('nodeSearch').value.toLowerCase();
  let filtered = state.nodes;
  if (search) filtered = filtered.filter(n => (n.name + ' ' + n.server).toLowerCase().includes(search));
  if (filtered.length === 0) {
    tbody.innerHTML = '';
    empty.style.display = 'block';
    return;
  }
  empty.style.display = 'none';
  tbody.innerHTML = filtered.map(n => {
    const tagClass = 'tag-' + (n.protocol === 'vmess' ? 'vmess' : n.protocol === 'vless' ? 'vless' : n.protocol === 'trojan' ? 'trojan' : 'ss');
    return \`<tr>
      <td><input type="checkbox" data-fp="\${escHtml(n.fingerprint)}" \${n.enabled ? 'checked' : ''} onchange="updateNodeEnabled(this)"></td>
      <td>\${escHtml(n.name)}</td>
      <td><span class="tag \${tagClass}">\${n.protocol}</span></td>
      <td style="font-size:12px">\${escHtml(n.server)}</td>
      <td>\${n.port}</td>
      <td>\${n.tls ? '✅' : '❌'}</td>
      <td><button class="btn btn-sm" onclick="copyNodeLink('\${escHtml(n.fingerprint)}')">📋 复制</button></td>
    </tr>\`;
  }).join('');
}

function filterNodes() { renderNodes(); }

// ============ 节点名清洗 ============

function cleanParams() {
  return {
    pattern: document.getElementById('cleanPattern').value,
    regex: document.getElementById('cleanRegex').checked,
  };
}

async function previewClean() {
  const box = document.getElementById('cleanPreviewBox');
  try {
    const res = await api('/nodes/clean/preview', { method: 'POST', body: JSON.stringify(cleanParams()) });
    const d = res.data || { count: 0, samples: [] };
    if (d.count === 0) {
      box.style.display = 'block';
      box.innerHTML = '✅ 没有节点名包含该片段';
      return;
    }
    const rows = d.samples.map((s) => \`<div style="margin:2px 0"><code style="color:var(--text2);text-decoration:line-through">\${escHtml(s.before)}</code> → <b>\${escHtml(s.after)}</b></div>\`).join('');
    box.style.display = 'block';
    box.innerHTML = \`<b>将影响 \${d.count} 个节点</b>（最多预览10条）：\${rows}<div style="color:var(--text2);margin-top:4px">确认无误后点「🧹 清洗」执行</div>\`;
  } catch (e) { toast('预览失败: ' + e.message, 'error'); }
}

async function applyClean() {
  const p = cleanParams();
  if (!p.pattern.trim()) { toast('请先输入要删除的片段', 'error'); return; }
  if (!confirm('确定清洗所有匹配的节点名？此操作直接修改存储的节点名。')) return;
  try {
    const res = await api('/nodes/clean', { method: 'POST', body: JSON.stringify(p) });
    toast(\`清洗完成，已重命名 \${res.data?.changed ?? 0} 个节点\`);
    document.getElementById('cleanPreviewBox').style.display = 'none';
    loadNodes();
  } catch (e) { toast('清洗失败: ' + e.message, 'error'); }
}

function copyNodeLink(fingerprint) {
  const node = state.nodes.find(n => n.fingerprint === fingerprint);
  if (!node || !node.link) { toast('节点链接不可用', 'error'); return; }
  navigator.clipboard.writeText(node.link)
    .then(() => toast('已复制单节点链接'))
    .catch(() => {
      const i = document.createElement('input');
      i.value = node.link; document.body.appendChild(i); i.select();
      document.execCommand('copy'); i.remove();
      toast('已复制单节点链接');
    });
}

function toggleSelectAll(cb) {
  document.querySelectorAll('#nodesTableBody input[type="checkbox"][data-fp]').forEach(c => { c.checked = cb.checked; });
  // 同步 state.nodes 的 enabled
  state.nodes.forEach(n => { n.enabled = cb.checked; });
  saveNodeEnabled();
}

function updateNodeEnabled(cb) {
  // 联动全选框状态
  const all = document.querySelectorAll('#nodesTableBody input[type="checkbox"][data-fp]');
  const allChecked = [...all].every(c => c.checked);
  document.getElementById('nodeSelectAll').checked = allChecked;
  // 同步 state.nodes 的 enabled（立即反映到输出节点数）
  const fp = cb.dataset.fp;
  if (fp) {
    const node = state.nodes.find(n => n.fingerprint === fp);
    if (node) node.enabled = cb.checked;
  }
  saveNodeEnabled();
}

// 保存启用列表（防抖，避免连续点击频繁请求）
let nodeSaveTimer = null;
function saveNodeEnabled() {
  clearTimeout(nodeSaveTimer);
  nodeSaveTimer = setTimeout(async () => {
    // 基于 state.nodes 全量数据构建（不受搜索过滤影响）
    const enabled = state.nodes.filter(n => n.enabled).map(n => n.fingerprint);
    try {
      await api('/nodes/enabled', { method: 'PUT', body: JSON.stringify({ enabled }) });
      toast('节点选择已保存');
    } catch (e) { toast('保存失败: ' + e.message, 'error'); }
  }, 400);
}

// ============ Output ============
function loadOutput() {
  refreshNodeCount();
  renderOutputUrls();
}

async function refreshNodeCount() {
  try {
    const data = await api('/nodes');
    state.nodes = data.data || [];
    const total = state.nodes.length;
    const enabled = state.nodes.filter(n => n.enabled !== false).length;
    document.getElementById('outputNodeCount').textContent = \`\${enabled} 个节点（共 \${total}）\`;
    // 同步节点页勾选状态（如果已加载）
    if (state.currentPage === 'nodes') renderNodes();
  } catch { toast('刷新节点数失败', 'error'); }
}

function renderOutputUrls() {
  const baseUrl = window.location.origin + '/sub';
  const formats = [
    { key: 'mihomo', name: '🐱 Mihomo', desc: 'Mihomo / Clash Meta / OpenClash / Stash' },
    { key: 'singbox', name: '📦 Sing-box', desc: 'Sing-box 原生格式' },
    { key: 'v2ray', name: '📄 V2ray', desc: 'V2ray 标准订阅 (Base64)' },
    { key: 'v2rayn', name: '📱 V2RayNG', desc: 'V2RayNG Android' },
    { key: 'nekoray', name: '🪐 NekoRay', desc: 'NekoRay / NekoBox' },
    { key: 'shadowrocket', name: '🚀 Shadowrocket', desc: 'Shadowrocket iOS' },
    { key: 'loon', name: '🌙 Loon', desc: 'Loon iOS' },
    { key: 'surge', name: '⚡ Surge', desc: 'Surge iOS / Mac' },
    { key: 'quantumultx', name: '🍁 Quantumult X', desc: 'Quantumult X iOS' },
  ];
  document.getElementById('outputLinks').innerHTML = formats.map(f => {
    const url = \`\${baseUrl}/\${f.key}/{key}\`;
    return \`<div class="sub-item" onclick="showConfigModal('\${f.key}', '\${f.name}')">
      <span class="name">\${f.name}</span>
      <span class="desc">\${f.desc}</span>
      <input value="\${url}" readonly onclick="event.stopPropagation();this.select()">
      <span class="sub-actions">
        <button class="btn btn-sm" onclick="event.stopPropagation();showQrModal('\${f.key}', '\${f.name}')">📱 二维码</button>
        <button class="btn btn-sm" onclick="event.stopPropagation();copyFormatUrl('\${f.key}')">📋 复制</button>
      </span>
    </div>\`;
  }).join('');
  // 异步获取订阅 key 后替换占位符
  loadSubKey();
}

let subKey = '';
async function loadSubKey() {
  try {
    const data = await api('/sub-key');
    subKey = data.data?.key || '';
    if (subKey) {
      document.querySelectorAll('#outputLinks input').forEach(input => {
        input.value = input.value.replace('{key}', subKey);
      });
    } else {
      document.querySelectorAll('#outputLinks input').forEach(input => {
        input.value = input.value.replace('{key}', '');
      });
    }
  } catch (e) {
    // 认证过期或网络异常：保持占位符并提示
    document.querySelectorAll('#outputLinks input').forEach(input => {
      input.value = input.value.replace('{key}', '');
    });
    const container = document.querySelector('#outputLinks');
    if (container) {
      const el = document.createElement('div');
      el.style.cssText = 'color:var(--red);font-size:12px;margin-top:8px;padding:8px;background:var(--bg);border-radius:10px';
      el.textContent = '⚠️ 无法获取订阅链接，请重新登录';
      container.appendChild(el);
    }
  }
}

function copyFormatUrl(format) {
  const url = \`\${window.location.origin}/sub/\${format}/\${subKey}\`;
  navigator.clipboard.writeText(url)
    .then(() => toast('已复制订阅链接'))
    .catch(() => {
      const i = document.createElement('input');
      i.value = url; document.body.appendChild(i); i.select();
      document.execCommand('copy'); i.remove();
      toast('已复制订阅链接');
    });
}

// ============ 二维码 ============
function showQrModal(format, name) {
  const url = encodeURIComponent(\`\${window.location.origin}/sub/\${format}/\${subKey}\`);
  if (!subKey) { toast('尚未获取订阅密钥，请刷新重试', 'error'); return; }
  document.getElementById('qrContainer').innerHTML = \`<img src="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=\${url}" alt="QR码" style="border-radius:8px">\`;
  document.getElementById('qrFormatName').textContent = name + ' 订阅';
  showModal('qrModal');
}

function copyUrl(url) {
  navigator.clipboard.writeText(url).then(() => toast('已复制')).catch(() => {
    // fallback
    const i = document.createElement('input');
    i.value = url; document.body.appendChild(i); i.select();
    document.execCommand('copy'); i.remove();
    toast('已复制');
  });
}

function showConfigModal(format, name) {
  showModal('configModal');
  document.getElementById('previewFormatSelect').value = format;
  document.getElementById('configPreview').textContent = '加载中...';
  previewConfig(format);
}

function previewSelect(force) {
  const select = document.getElementById('previewFormatSelect');
  const format = select.value;
  // onchange 自动加载（点击行进入时也可能触发，force 仅语义化）
  void force;
  previewConfig(format);
}

async function previewConfig(format) {
  document.getElementById('configPreview').textContent = '加载中...';
  try {
    const res = await fetch(\`/api/output/\${format}\`, { credentials: 'include' });
    if (!res.ok) throw new Error('加载失败');
    const text = await res.text();
    document.getElementById('configPreview').textContent = text;
  } catch (e) {
    document.getElementById('configPreview').textContent = '加载失败: ' + e.message;
  }
}

async function downloadConfig(format, filename) {
  try {
    const res = await fetch(\`/api/output/\${format}\`, { credentials: 'include' });
    const blob = await res.blob();
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = filename; a.click();
    URL.revokeObjectURL(a.href);
    toast('下载完成');
  } catch { toast('下载失败', 'error'); }
}

/** 各格式对应的标准配置文件名后缀（客户端直接识别的文件名和类型） */
const CONFIG_FILE_NAMES = {
  mihomo:        'mihomo.yaml',
  singbox:       'sing-box.json',
  v2ray:         'v2ray.txt',
  v2rayn:        'v2rayn.txt',
  nekoray:       'nekoray.txt',
  shadowrocket:  'shadowrocket.conf',
  loon:          'loon.conf',
  surge:         'surge.conf',
  quantumultx:   'quantumultx.conf',
};

/** 读取预览弹窗当前选中的格式，按客户端标准文件名下载 */
function downloadConfigByFormat() {
  const format = document.getElementById('previewFormatSelect').value;
  const filename = CONFIG_FILE_NAMES[format] || \`subscription.\${format}\`;
  downloadConfig(format, filename);
}

async function downloadMihomo() { downloadConfig('mihomo', 'mihomo.yaml'); }
async function downloadSingbox() { downloadConfig('singbox', 'sing-box.json'); }

// ============ 输出页主操作条（A：格式选择器驱动） ============
function getOutputFormat() {
  return document.getElementById('outputFormatSelect').value;
}

function copyOutputFormatUrl() {
  copyFormatUrl(getOutputFormat());
}

function downloadOutputFormat() {
  const format = getOutputFormat();
  const filename = CONFIG_FILE_NAMES[format] || \`subscription.\${format}\`;
  downloadConfig(format, filename);
}

function showQrOutputFormat() {
  showQrModal(getOutputFormat(), document.getElementById('outputFormatSelect').selectedOptions[0].textContent);
}

function previewOutputFormat() {
  showConfigModal(getOutputFormat(), document.getElementById('outputFormatSelect').selectedOptions[0].textContent);
}

function onOutputFormatChange() {
  // 预留：将来可联动刷新节点数或自动预加载
}

// ============ Settings ============
async function loadSettings() {
  try {
    const data = await api('/settings');
    document.getElementById('settingAppName').value = data.data?.app_name || '';
  } catch {}
  loadCatalogStatus();
  searchCatalog(); // 默认显示前 100 个分类
}

async function saveSettings() {
  const appName = document.getElementById('settingAppName').value.trim();
  try {
    await api('/settings', { method: 'PUT', body: JSON.stringify({ app_name: appName }) });
    toast('设置已保存');
    // 立即刷新页面标题
    document.getElementById('sidebarLogo').textContent = appName;
    document.getElementById('loginTitle').textContent = '🔐 ' + appName;
    document.title = appName;
  } catch (e) { toast('保存失败: ' + e.message, 'error'); }
}

// ============ 账号安全（用户名/密码） ============

async function loadCurrentUsername() {
  try {
    const res = await api('/auth/username');
    const el = document.getElementById('currentUsername');
    if (el) el.textContent = res.data?.username || 'admin';
  } catch {}
}

async function changeUsername() {
  const newUsername = document.getElementById('settingNewUsername').value.trim();
  const currentPassword = document.getElementById('settingUsernamePassword').value;
  if (!newUsername || !currentPassword) { toast('请填写新用户名和当前密码', 'error'); return; }
  try {
    await api('/auth/username', { method: 'POST', body: JSON.stringify({ currentPassword, newUsername }) });
    toast('用户名修改成功，下次登录使用新用户名');
    document.getElementById('settingNewUsername').value = '';
    document.getElementById('settingUsernamePassword').value = '';
    loadCurrentUsername();
  } catch (e) { toast('修改失败: ' + e.message, 'error'); }
}

async function changePassword() {
  const currentPassword = document.getElementById('settingOldPassword').value;
  const newPassword = document.getElementById('settingNewPassword').value;
  const confirm2 = document.getElementById('settingNewPassword2').value;
  if (!currentPassword || !newPassword) { toast('请填写旧密码和新密码', 'error'); return; }
  if (newPassword.length < 6) { toast('新密码至少6位', 'error'); return; }
  if (newPassword !== confirm2) { toast('两次输入的新密码不一致', 'error'); return; }
  try {
    await api('/auth/password', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) });
    toast('密码修改成功，请重新登录');
    setTimeout(() => location.reload(), 1200);
  } catch (e) { toast('修改失败: ' + e.message, 'error'); }
}

// ============ 规则库管理（设置页） ============

/** 加载目录状态（更新时间/总数/失效数） */
async function loadCatalogStatus() {
  try {
    const res = await api('/rules/catalog/meta');
    const meta = res.data?.meta || {};
    const removed = res.data?.removed || [];
    const statusEl = document.getElementById('catalogStatus');
    const removedSection = document.getElementById('catalogRemovedSection');
    const removedCount = document.getElementById('catalogRemovedCount');

    if (meta.status === 'never') {
      statusEl.innerHTML = '⚠️ 尚未同步过规则库，点击「立即刷新」开始同步';
      return;
    }

    const statusText = meta.status === 'stale' ? '🟡 数据过期' : '🟢 正常';
    const lastUpdate = meta.fetchedAt ? new Date(meta.fetchedAt).toLocaleString('zh-CN') : '未知';
    statusEl.innerHTML = \`
      <div style="display:flex;flex-wrap:wrap;gap:12px;font-size:13px">
        <span>\${statusText}</span>
        <span>上次更新: \${lastUpdate}</span>
        <span>分类总数: \${meta.total ?? 0}</span>
        <span>已失效移除: \${meta.removedCount ?? 0}</span>
      </div>
      \${meta.lastError ? \`<div style="color:var(--red);font-size:12px;margin-top:4px">上次错误: \${escHtml(meta.lastError)}</div>\` : ''}
    \`;

    if (removed.length > 0) {
      removedSection.style.display = 'block';
      removedCount.textContent = removed.length;
      document.getElementById('catalogRemovedList').innerHTML = removed.map(r =>
        \`<div style="display:flex;justify-content:space-between;padding:6px 8px;border-bottom:1px solid var(--border);font-size:12px">
          <span style="color:var(--red)">\${escHtml(r.id)}</span>
          <span style="color:var(--text2)">\${new Date(r.removedAt).toLocaleString('zh-CN')}</span>
        </div>\`
      ).join('');
    }
  } catch {
    document.getElementById('catalogStatus').innerHTML = '❌ 加载规则库状态失败';
  }
}

/** 手动刷新规则库 */
async function refreshCatalog() {
  const btn = document.getElementById('catalogRefreshBtn');
  btn.disabled = true;
  btn.textContent = '⏳ 刷新中…';
  try {
    const res = await api('/rules/catalog/refresh', { method: 'POST' });
    if (res.success) {
      toast('✅ 规则库刷新完成');
      // 重新加载状态和搜索
      loadCatalogStatus();
      // 清空搜索缓存，下次搜索走新数据
      catalogAll = [];
      const searchEl = document.getElementById('catalogSearch');
      if (searchEl.value) debouncedSearchCatalog();
    } else {
      toast('❌ 刷新失败: ' + (res.error?.message || '未知错误'), 'error');
    }
  } catch (e) {
    toast('❌ 刷新失败: ' + e.message, 'error');
  } finally {
    btn.disabled = false;
    btn.textContent = '🔄 立即刷新';
  }
}

/** 展开/收起失效历史 */
function toggleRemovedHistory() {
  const list = document.getElementById('catalogRemovedList');
  const toggle = document.getElementById('catalogRemovedToggle');
  if (list.style.display === 'none') {
    list.style.display = 'block';
    toggle.textContent = '▼';
  } else {
    list.style.display = 'none';
    toggle.textContent = '▶';
  }
}

// ============ 规则库（设置页） ============
let catalogAll = [];      // 全量 1546 分类
let catalogSearchTimer = null;
let catalogType = '';     // 当前分类筛选：'' | 'aggregate' | 'site' | 'tld'
let addRuleGroupOptions = []; // 目标分组下拉选项

/** 点击分类筛选 chip */
function setCatalogType(btn) {
  catalogType = btn.dataset.type || '';
  document.querySelectorAll('.catalog-chip').forEach(c => {
    c.classList.toggle('active', (c.dataset.type || '') === catalogType);
  });
  searchCatalog();
}

// 首次进入设置页时加载 catalog 和分组下拉（只加载一次，后续复用）
async function ensureCatalogLoaded() {
  try {
    if (catalogAll.length === 0) {
      const groupsRes = await api('/rules/groups');
      const groups = groupsRes.data?.groups || [];
      // 缓存分组下拉选项
      addRuleGroupOptions = groups.map(g => ({ key: g.key, name: g.icon + ' ' + g.name }));
      // 加载 catalog 元信息（数量）
      const catRes = await api('/rules/catalog?limit=1');
      const total = catRes.data?.meta?.total ?? 0;
      document.getElementById('catalogCount').textContent = total ? \`共 \${total} 个分类\` : '';
      // 预填分组下拉
      const sel = document.getElementById('addRuleGroup');
      sel.innerHTML = addRuleGroupOptions.map(o => \`<option value="\${escHtml(o.key)}">\${escHtml(o.name)}</option>\`).join('');
    }
  } catch { /* catalog 加载失败静默，搜索时会再尝试 */ }
}

function debouncedSearchCatalog() {
  clearTimeout(catalogSearchTimer);
  catalogSearchTimer = setTimeout(searchCatalog, 250);
}

async function searchCatalog() {
  const q = document.getElementById('catalogSearch').value.trim();
  const list = document.getElementById('catalogList');
  list.innerHTML = '<div style="color:var(--text2);padding:16px;text-align:center">⏳ 搜索中…</div>';
  try {
    const limit = q ? 200 : 200;
    const params = new URLSearchParams();
    if (catalogType) params.set('type', catalogType);
    if (q) params.set('q', q);
    params.set('limit', String(limit));
    const res = await api(\`/rules/catalog?\${params.toString()}\`);
    const items = res.data?.catalog || [];
    const total = res.data?.meta?.total || 0;
    // 更新各分类计数徽标（首次加载后也填充）
    const typeCounts = res.data?.meta?.typeCounts;
    if (typeCounts) {
      document.querySelectorAll('.catalog-chip-count').forEach(badge => {
        const key = badge.dataset.count;
        badge.textContent = typeCounts[key] ?? badge.textContent;
      });
    }
    if (items.length === 0) {
      list.innerHTML = \`<div style="color:var(--text2);padding:16px;text-align:center">\${q ? '未找到匹配的分类' : '暂无数据，请先同步规则库'}</div>\`;
      return;
    }
    list.innerHTML = items.map(it => \`
      <div class="catalog-item" data-id="\${escHtml(it.id)}" data-label="\${escHtml(it.label || it.id)}" style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;border-radius:8px" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background='transparent'">
        <div style="display:flex;align-items:center;gap:10px;min-width:0">
          <span style="font-weight:600">\${escHtml(it.id)}</span>
          <span style="color:var(--text2);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\${escHtml(it.label || '')}</span>
          <span style="color:var(--text2);font-size:11px;background:var(--bg);padding:2px 8px;border-radius:20px">\${it.type}</span>
        </div>
        <button class="btn btn-sm add-rule-btn">➕ 加入</button>
      </div>\`).join('') +
      (total > items.length ? \`<div style="text-align:center;padding:12px"><button class="btn btn-sm" onclick="showAllCatalog()" id="showAllBtn">📋 显示全部 \${total} 个分类</button></div>\` : '');
    document.querySelectorAll('.add-rule-btn').forEach(btn => {
      btn.addEventListener('click', function() {
        const item = this.closest('.catalog-item');
        if (item) openAddRule(item.dataset.id || '', item.dataset.label || '');
      });
    });
  } catch { list.innerHTML = '<div style="color:var(--red);padding:16px;text-align:center">❌ 搜索失败</div>'; }
}

/** 显示全部 1899 个分类 */
async function showAllCatalog() {
  const btn = document.getElementById('showAllBtn');
  if (btn) { btn.disabled = true; btn.textContent = '⏳ 加载中…'; }
  try {
    const res = await api('/rules/catalog?limit=5000');
    const items = res.data?.catalog || [];
    document.getElementById('catalogList').innerHTML = items.map(it => \`
      <div class="catalog-item" data-id="\${escHtml(it.id)}" data-label="\${escHtml(it.label || it.id)}" style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;border-radius:8px" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background='transparent'">
        <div style="display:flex;align-items:center;gap:10px;min-width:0">
          <span style="font-weight:600">\${escHtml(it.id)}</span>
          <span style="color:var(--text2);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\${escHtml(it.label || '')}</span>
          <span style="color:var(--text2);font-size:11px;background:var(--bg);padding:2px 8px;border-radius:20px">\${it.type}</span>
        </div>
        <button class="btn btn-sm add-rule-btn">➕ 加入</button>
      </div>\`).join('');
    document.querySelectorAll('.add-rule-btn').forEach(btn => {
      btn.addEventListener('click', function() {
        const item = this.closest('.catalog-item');
        if (item) openAddRule(item.dataset.id || '', item.dataset.label || '');
      });
    });
  } catch { document.getElementById('catalogList').innerHTML = '<div style="color:var(--red);padding:16px;text-align:center">❌ 加载失败</div>'; }
}

function openAddRule(id, label) {
  document.getElementById('addRuleId').value = id;
  document.getElementById('addRuleLabel').value = label || id;
  const groupSel = document.getElementById('addRuleGroup');
  groupSel.value = 'other';
  document.getElementById('addRuleModal').classList.add('show');
}

async function confirmAddRule() {
  const id = document.getElementById('addRuleId').value.trim();
  const label = document.getElementById('addRuleLabel').value.trim() || id;
  const groupKey = document.getElementById('addRuleGroup').value;
  // 根据分组自动推断目标策略：广告拦截→REJECT，国内直连→DIRECT，其余→PROXY
  const target = groupKey === 'ads' ? 'REJECT' : groupKey === 'china-direct' ? 'DIRECT' : 'PROXY';
  if (!id) { toast('分类 ID 无效', 'error'); return; }
  try {
    await api('/rules/custom', {
      method: 'POST',
      body: JSON.stringify({ id, label, groupKey, target }),
    });
    toast('✅ 已加入规则库');
    closeModal('addRuleModal');
    // 刷新规则页，让新规则出现在对应分组；并清空搜索框恢复初始态
    if (typeof RULE_GROUPS !== 'undefined') { RULE_GROUPS = []; }
    if (window.pageRules) { /* no-op */ }
  } catch (e) { toast('加入失败: ' + e.message, 'error'); }
}

async function deleteCustomRule(id) {
  if (!id) return;
  if (!confirm('确定要从分流规则中删除「' + id + '」吗？')) return;
  try {
    await api('/rules/custom/' + encodeURIComponent(id), { method: 'DELETE' });
    toast('✅ 已删除规则: ' + id);
    // 刷新规则页，移除该规则
    if (typeof RULE_GROUPS !== 'undefined') { RULE_GROUPS = []; }
    loadRules();
  } catch (e) { toast('删除失败: ' + e.message, 'error'); }
}

// ============ Utils ============
function escHtml(s) { return String(s).replace(/[&<>"']/g, function(m) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]; }); }

// ============ 项目信息 + 升级检测 ============
let metaLoaded = false;
async function loadMeta() {
  if (metaLoaded) return;
  metaLoaded = true;
  try {
    const metaRes = await api('/meta');
    const meta = metaRes.data?.meta || {};
    const appName = metaRes.data?.app_name || meta.name || 'CF-Workers-SUB-Next';
    const ver = meta.version || '-';
    document.getElementById('appVersion').textContent = ver;
    document.getElementById('loginVersion').textContent = ver;
    // 动态替换站点名称
    document.getElementById('sidebarLogo').textContent = appName;
    document.getElementById('loginTitle').textContent = '🔐 ' + appName;
    document.title = appName;
  } catch { /* 版本信息加载失败静默 */ }

  // 升级检测（静默，不阻塞页面）
  try {
    const upRes = await api('/meta/check-upgrade');
    const up = upRes.data || {};
    const el = document.getElementById('upgradeStatus');
    if (up.hasUpdate && up.latest) {
      el.innerHTML = '<span class="upgrade-banner">🆕 发现新版本 <a href="' + escHtml(up.releaseUrl || '') + '" target="_blank" rel="noopener">v' + escHtml(up.latest) + '</a></span>';
    }
  } catch { /* 升级检测失败忽略 */ }
}

// ============ Init ============
window.addEventListener('DOMContentLoaded', async () => {
  // 从 hash 恢复页面
  const savedPage = window.location.hash.replace('#', '') || 'dashboard';
  if (['dashboard','subscribe','nodes','rules','output','settings'].includes(savedPage)) {
    state.currentPage = savedPage;
  }
  loadMeta();
  await checkSession();
  switchPage(state.currentPage);
});

window.addEventListener('hashchange', () => {
  const page = window.location.hash.replace('#', '') || 'dashboard';
  if (['dashboard','subscribe','nodes','rules','output','settings'].includes(page)) {
    switchPage(page);
  }
});
</script>
</body>
</html>`;
export default HTML;
